 version: "3"
 services:
  app:
    build: 
      context: ./src
      dockerfile: Dockerfile.prod
      target: base
    container_name: server
    env_file:
      - ./src/.env
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 81:80    
    

  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: Iyanu
      MYSQL_ROOT_PASSWORD: Iyanuoluwa@27
    ports:
      - "3309:3306"
    volumes:
      - ./mysql/init.sql:/data/application/init.sql
      - mysql_data:/var/lib/mysql   
  
 volumes:
   mysql_data:

